### ISSUE TITLE
VUR

### ISSUE THREAD

**Issue by zen0bit** [123randomuser321/123randomuser321_void_templates#1]
I know, you do not intend to submit these..
but don't you wanna push them to my unofficial repo?
[VUR](https://github.com/oSoWoSo/VUR)

I wanna gather every templates posible to it.

Actually I am creating spin distribution with support to VUR included...

Cheers and happy voiding :+1:

**Comment by 123randomuser321** [comment]
I'll get back on this once I am done whipping this repo into shape.
(There are some things I am currently not satisfied with)

**Comment by 123randomuser321** [comment]
Update: 
There are a lot of things I am not satisfied with, but I haven't forgotten.

**Comment by 123randomuser321** [comment]
Well well...

As it turns out I kinda lack the motivation needed to maintain packages.
As I only really update them when I notice an update (happens sporadically), I am not really comfortable with pushing them into someone's upstream and adopting maintainership.

So, consider these up for adoption, feel free to merge them, but do not expect me to maintain them.

Hope this doesn't sound too bad.
